version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"

  # client_mobile: # Mobile not working yet
  #   build:
  #     context: .
  #     dockerfile: apps/front-mobile/Dockerfile
  #   volumes:
  #     - ./shared:/shared
  #   command: sh -c "npm run build && cp /app/android/app/build/outputs/apk/release/app-release.apk /shared/client.apk"

  client_web:
    build:
      context: .
      dockerfile: apps/front-web/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      # - client_mobile
      - server
    volumes:
      - ./shared:/shared