version: "3.9"
# Version qui par defaut overide le docker-compose avec les volumes pour le dev
services:
  server:
    volumes:
      - ./server:/app:delegated
      - server_node_modules:/app/node_modules
    command: npm run dev
  client_web:
    volumes:
      - ./client_web:/web:delegated
      - client_node_modules:/web/node_modules
      - shared_data:/shared
    depends_on:
      - server
      - client_mobile
    command: sh -c "/usr/local/bin/wait-for-file.sh /shared/client.apk 60 npm run dev"
  client_mobile:
    volumes:
      - ./client_mobile:/mobile:delegated
      - shared_data:/shared
    command: /mobile/build.sh
volumes:
  server_node_modules:
  client_node_modules:
  shared_data:
